language: php

php:
  - 8.0
  - 8.1
  - 8.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 8.0
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
      dist: precise
    - php: 8.0
      env: SYMFONY_VERSION='5.4.*'
    - php: 8.1
      env: SYMFONY_VERSION='6.2.*'
    - php: 8.2
      env: SYMFONY_VERSION='6.2.*'

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev symfony/framework-bundle:${SYMFONY_VERSION} --no-update; fi

install: composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit
